### PR TITLE
Create get_tickets_comment

### PR DESCRIPTION
**Pull request by k-dutra**
Function to fetch comments/replies of a single ticket.

### CODE REVIEW

**Comment by chrisumphlett** [comment]
Thank you! In order to not complicate things, I won't make any changes directly, I'll let you handle. Below are some things I did, that you should repeat.
some FYIs. 
* I ran `devtools::document()` to update the documentation files. Those will show up as addtl changes here
* I ran `devtools::check()` to verify there weren't any issues, which revealed that the new file was not named properly -- it didn't have a .R extension (were you working in RStudio? It usually gets .R by default). I added an 's' to the end of the file name and .R as the extension, then ran these 2 functions again.

Once I fixed that, `check()` found some other issues. These are mostly persnickety things that are because this is a package, nothing to do with the functionality of the code itself.

image

The first group has to do with the parameters not being included in the Roxygen function. Look at another .R file in the R folder and you'll find an example of things that need to be included besides just the function name and description.

The 2nd one is fixed by putting `attachments` in quotes in that `mutate` --> "attachments".

**Comment by k-dutra** [comment]
Thank you! I was learning today how to use Roxigen2. I hope that now everything works well, but if I need change something other time, just tell me. I think that I don't need to change NAMESPACE, DESCRIPTION files, just this one with a better roxygen comments, right?

**Comment by chrisumphlett** [comment]
NAMESPACE updates automatically when you run `devtools::document()` (in addition to it creating the .md doc files). DESCRIPTION does get manually updated, but you don't need to change it. I already incremented the version number. the only other change that would be needed there is if you had utilized a different package than what I was already using (besides something from base R), that would be listed as an import/dependency.

Thanks for doing that, I'll pull down the updates and look at it again during the day tomorrow

**Comment by k-dutra** [comment]
Cool, I'm glad to hear that! I just used some packages that was already in your NAMESPACE and DESCRIPTION. Thus, I believe/hope that tomorrow everything will run well.

**Comment by chrisumphlett** [comment]
Thanks this is super helpful. I made some changes to the function description, some of it was changing the english a bit and most of the rest was adding more line breaks (general good practice is to keep line length <= 80 characters-- I forgot to mention that before).

I renamed `sensitive_data` to `metadata` because that more strictly describes what it returns. Some of those columns are not sensitive. But I agree that the warning should still be in the function description, I re-wrote that a bit.

I added `tidyselect` to the import because of the `all_of()` function. Had to add this to DESCRIPTION as well.

Same for the function code, I added some line breaks and got rid of trailing spaces. No changes to how it functions.

For testing, I tested it as part of the package (rather than just loading the function on its own) by using `devtools::load_all()`. This revealed one problem I fixed

* `select(all_of(columns_final))` has an error if not including sensitive data or using `add_cols`. I added the highlighted code 
image

Ran `document()` and `check()` again.

Then ran `check_rhub()` and `check_win_devel()` which is part of what is required before submitting to CRAN (See the cran comments file). I am awaiting those results right now.

**Comment by chrisumphlett** [comment]
Before I close this, i'm going to get the results from rhub/win_devel, and give you a chance to review and see if you have any questions.
Then there's a few simple steps to go through for tagging the release in GH and submitting to CRAN.

**Comment by chrisumphlett** [comment]
the check is failing on mac-os because of the R version. not concerned. very little concern about a failure on mac that doesn't happen on windows.

**Review by k-dutra — COMMENTED** [review]
Thanks Chris, I agree with every change.

**Comment by k-dutra** [comment]
I have a question about this failure on Mac and the CRAN answer. Is there any impact on CRAN accepting the changes in the package? And is there something that we can do to solve this failure? And how long do they usually take to answer the changes submitted?

Thank you again for the opportunity, I'm glad and I've enjoyed contributing.

**Comment by chrisumphlett** [comment]
I made a video to give you a better and more comprehensive answer to your questions. It's about 7.5mins long.
I also showed the process that I'll follow to send to CRAN, I'm going to do that soon after I merge the PR and tag the release on GH.

https://app.screencast.com/aRDNviPXPEOI6 -- Sorry I can't see a way to embed this, and the file was too large to upload here.

**Comment by k-dutra** [comment]
Thank you a lot for the video! I really appreciate your attention and sharing of knowledge. I hope to find more professionals like you in my path.

As you said in the video, the release was super fast. That's great! Many thanks again, Chris!

**Pull request merged**
